name: midigen
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - fastapi=0.104.1
  - uvicorn=0.24.0
  - numpy=1.24.3
  - protobuf=3.20.3
  - python-multipart=0.0.6
  - pip:
    - tensorflow==2.12.0
    - magenta==2.1.4
    - numba==0.49.1
    - llvmlite==0.31.0
    - python-rtmidi==1.5.8 