name: midigen
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - fastapi
  - uvicorn
  - numpy
  - protobuf
  - python-multipart
  - pip:
    - tensorflow
    - magenta
    - python-rtmidi
    - numba
    - llvmlite 