name: midigen
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip
  - fastapi
  - uvicorn
  - numpy
  - protobuf
  - python-multipart
  - numba=0.56.4
  - llvmlite=0.39.1
  - cmake
  - pip:
    - tensorflow==2.9.1
    - magenta==2.1.4
    - python-rtmidi==1.1.2 